"""
Django settings for chaibase project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from corsheaders.defaults import default_headers

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, "static")


def _env(var, default=None):
    '''
    docstring for chaibase_env
    '''
    return os.environ.get('CHAIBASE_%s' % var, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pjvn8e5l%t(7948)^w9-wbhq=r%=ir2)#2u)tegq5q4dr-yniv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '0.0.0.0',
]

CORS_ORIGIN_WHITELIST = ALLOWED_HOSTS + [
    '0.0.0.0:4200',
]

CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'tokenapi',
    'django_google_maps',
    'phonenumber_field',
    'django_extensions',

    'chaibase.core',
    'chaibase.importers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

CORS_ALLOW_HEADERS = default_headers + (
    'X-Fingerprint',
    'Authorization',
)

ROOT_URLCONF = 'chaibase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chaibase.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': _env(
            'DATABASE_ENGINE', 'django.db.backends.postgresql_psycopg2'),
        'NAME': _env('DATABASE_NAME', 'chaibase'),
        'USER': _env('DATABASE_USER', 'chaibase'),
        'PASSWORD': _env('DATABASE_PASSWORD', 'chaibase'),
        'HOST': _env('DATABASE_HOST', '127.0.0.1'),
        'PORT': _env('DATABASE_PORT', 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.UserAttributeSimilarityValidator'),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.MinimumLengthValidator'),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.CommonPasswordValidator'),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.NumericPasswordValidator'),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

AUTH_USER_MODEL = 'core.User'

GOOGLE_MAPS_API_KEY = 'AIzaSyD8uCfIsh0qv8wcuj4jzvlflhWNrO3MzwU'

DEMO_FACTORY = "demo"

AUTHENTICATION_BACKENDS = [
    'tokenapi.backends.TokenBackend',
    'django.contrib.auth.backends.ModelBackend',

]

APPEND_SLASH = False
