# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170527_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A'), (2, 'A+'), (3, 'B'), (4, 'B+'), (5, 'C'), (-1, 'Unknown')], default=-1),
        ),
    ]
