# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entry_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(default=0.0)),
                ('reason', models.PositiveSmallIntegerField(choices=[(4, 'Burnt'), (5, 'Coarse'), (2, 'Stick'), (3, 'Tare'), (6, 'Tea'), (-1, 'Unknown'), (1, 'Water')], default=-1)),
                ('weighment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='core.Weighment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
